[package]
name = "RustyMft"
version = "0.1.0"
authors = ["matthew seyer <matthew.seyer@gmail.com>", "Omer Ben-Amram <omerbenamram@gmail.com>"]
edition = "2018"

[lib]
name = "rustymft"

[dependencies]
log = "0.4.6"
clap = "2.33.0"
encoding = "0.2.33"
byteorder = "1.3.1"
bitflags = "1.0.4"
serde = {version = "1.0.91", features = ["derive"]}
serde_json = "1.0.39"
seek_bufread = "~1.2"
env_logger = "0.6.1"

[dependencies.jmespath]
version = "^0.1.1"

[dependencies.r-winstructs]
version = "*"
branch = "master"
git = "https://github.com/forensicmatt/r-winstructs"

[dependencies.chrono]
version = "0.4.6"
features = ["serde"]
