[package]
name = "mft"
description = "A Fast (and safe) parser for the Windows Master File Table (MFT) format"
homepage = "https://github.com/omerbenamram/mft"
repository = "https://github.com/omerbenamram/mft"
license = "MIT/Apache-2.0"
readme = "README.md"

version = "0.1.2-alpha.0"
authors = ["Omer Ben-Amram <omerbenamram@gmail.com>", "matthew seyer <matthew.seyer@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4.6"
clap = "2.33.0"
encoding = "0.2.33"
byteorder = "1.3.1"
bitflags = "1.0.4"
serde = {version = "1.0.91", features = ["derive"]}
serde_json = "1.0.39"
env_logger = "0.6.1"
snafu = "0.2.3"
winstructs = "0.1.0"

[dependencies.jmespath]
version = "^0.1.1"

[dependencies.chrono]
version = "0.4.6"
features = ["serde"]

[[bin]]
name = "mft_dump"
