[package]
name = "RustyMft"
version = "0.1.0"
authors = ["matthew seyer <matthew.seyer@gmail.com>", "Omer Ben-Amram <omerbenamram@gmail.com>"]
edition = "2018"

[lib]
name = "rustymft"

[dependencies]
log = "*"
clap = "*"
encoding = "0.2"
byteorder = "*"
bitflags = "0.7"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"
seek_bufread = "~1.2"
env_logger = "0.3"

[dependencies.jmespath]
version = "^0.1.1"

[dependencies.r-winstructs]
version = "*"
branch = "master"
git = "https://github.com/forensicmatt/r-winstructs"

[dependencies.chrono]
version = "0.4.6"
features = ["serde"]
